### PR TITLE
Replaced HomeAssistantType with HomeAssistant

### PR DESCRIPTION
**Pull request by barteksalsa**
Replaced HomeAssistantType with HomeAssistant due to changes in Home Assistant

### CODE REVIEW

**Comment by gadulowaty** [comment]
OK. Approved.

**Review by gadulowaty — COMMENTED** [review]
Should work again.

**Review by gadulowaty — APPROVED** [review]
Approved

**Comment by dgtal1** [comment]
Thanks @barteksalsa ! I missed this copletely and checked it just today. In the meanwhile I merged #36 from @gadulowaty which contained your fix and some other fixes, so we do not need this PR any longer. Closing

**Pull request closed without merging**
